### ISSUE TITLE
Music Loading Failed

### ISSUE THREAD

**Issue by sandorfimarci** [OxygenCobalt/Auxio#120]
I get "Music loading failed" error on Android 9. (The library scan works great with Phonogram and other music players.)

Steps:

Install app
Press "Allow" for the storage permission prompt
App says "Music Loading failed"
Retry does nothing

Device: Huawei
Model: P20 Lite
Android: 9

Log:

```
2022-04-13 12:01:51.935 8056-8081/? E/Auxio.MusicStore: Music loading failed.
2022-04-13 12:01:51.936 8056-8081/? E/Auxio.MusicStore: java.lang.NullPointerException: fileName must not be null
        at org.oxycblt.auxio.music.MusicLoader.load(MusicLoader.kt:38)
        at org.oxycblt.auxio.music.MusicStore$Companion$initInstance$response$1.invokeSuspend(MusicStore.kt:8)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Comment by OxygenCobalt** [comment]
Seems like a device-specific issue where the `DISPLAY_NAME` field is not present. I'll try to fix it when I get the time.

**Comment by OxygenCobalt** [comment]
Can you try out this APK @sandorfimarci? Rename the extension from ZIP to APK. I added some extra checks to hopefully avoid this issue.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/8735091/app-debug.zip)

**Comment by sandorfimarci** [comment]
Yes, it works like a charm! Thanks
