### ISSUE TITLE
Crash when trying to open file

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#176]
#### Describe the bug/crash:

Auxio crashes if trying to open a music file.

#### Expected behavior

The file is played.

#### Steps To Reproduce the bug/crash:
1. Open a file using some kind of file manager
2. It crashes.

#### Logs/Stack Traces:

```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: org.oxycblt.auxio, PID: 30105
java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'DefaultDispatcher-worker-2'
Expected thread: 'main'
See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
	at com.google.android.exoplayer2.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:17)
	at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentMediaItemIndex(ExoPlayerImpl.java:1)
	at org.oxycblt.auxio.playback.system.PlaybackService.onSeek(PlaybackService.kt:3)
	at org.oxycblt.auxio.playback.state.PlaybackStateManager.seekTo(PlaybackStateManager.kt:3)
	at org.oxycblt.auxio.playback.PlaybackViewModel.play$enumunboxing$(PlaybackViewModel.kt:17)
	at org.oxycblt.auxio.playback.PlaybackViewModel.play$default(PlaybackViewModel.kt:3)
	at org.oxycblt.auxio.playback.PlaybackViewModel.performActionImpl(PlaybackViewModel.kt:13)
	at org.oxycblt.auxio.playback.PlaybackViewModel.onLibraryChanged(PlaybackViewModel.kt:2)
	at org.oxycblt.auxio.music.IndexerService.onIndexerStateChanged(IndexerService.kt:17)
	at org.oxycblt.auxio.music.Indexer.emitCompletion(Indexer.kt:8)
	at org.oxycblt.auxio.music.Indexer.index(Indexer.kt:22)
	at org.oxycblt.auxio.music.Indexer$index$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fe0a3ae, Dispatchers.Default]
```

#### Phone Information:

Stock Android 11.

#### Due Diligence:
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Seems like the background thread switches to the `Default` dispatcher (despite me specifying it as the Main dispatcher, ??????).

Can you try this apk?
[Auxio_CoroutineInsanity.zip](https://github.com/OxygenCobalt/Auxio/files/9029091/Auxio_CoroutineInsanity.zip)

**Comment by OxygenCobalt** [comment]
Okay, great. I'll keep that insane edge-case in the back of my head.
