### ISSUE TITLE
Crash while skipping songs

### ISSUE THREAD

**Issue by tate56** [OxygenCobalt/Auxio#239]
I looked for this in the issues tab but couldn't find it, but if I'm making a new thread for a documented bug, my apologies.
Basically, when I skip songs (might be triggered by doing it "quickly") I eventually get this crash. It's consistent if I skip enough songs. Does not seem to indicate a problem with the files I'm using based on the fact I can play whatever song I would have been skipping to, manually. This bug does not seem to appear in 2.6.1(using the fdroid repo). Began after updating to 2.6.3, and resolves if I downgrade back to 2.6.1.

#### Steps To Reproduce the bug/crash:
1. Skip songs (quickly?)
2. Crash

#### Logcat dump
```
--------- beginning of crash
09-14 09:18:56.139 10207 10207 E AndroidRuntime: FATAL EXCEPTION: main
09-14 09:18:56.139 10207 10207 E AndroidRuntime: Process: org.oxycblt.auxio, PID: 10207
09-14 09:18:56.139 10207 10207 E AndroidRuntime: java.lang.IllegalStateException: Slider value(-1.0) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(1407.0)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:201)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:8)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.draw(View.java:23898)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22767)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22714)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:5440)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:797)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8669)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
09-14 09:18:56.139 10207 10207 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
09-14 09:18:56.161 10207 10207 I Process : Sending signal. PID: 10207 SIG: 9
```

#### Phone Information:
Samsung S20+ 5G, Android 12, Dark Mode if that matters

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Yep, this was fixed in #231. I implemented smooth seeking by reducing the internal in which I polled for the position, however, in special situations, it would poll a position that was -1 (i.e the position during buffering), causing a crash since the SeekBar doesn't expect a -1 value. It should be fixed in the next version.

**Comment by OxygenCobalt** [comment]
I'll pin this issue for now to signify that it's waiting for the next version. Always a bit annoyed when I introduce a common bug but can't push a fix since it's bundled into a major version with several other additions that will take weeks/months to resolve.

**Comment by OxygenCobalt** [comment]
I'm aiming to release a patch for this issue this weekend.
