### ISSUE TITLE
Crash when choosing a folder

### ISSUE THREAD

**Issue by xfarrow** [OxygenCobalt/Auxio#311]
### Describe the Bug/Crash

In the settings it is possible to choose a folder to choose the music from. When clicking on "Add", app crashes.

### Describe the intended behavior

Should open folder

### What android version do you use?

Android 11

### What device model do you use?

Redmi Note 11 S

### Relevant log output

```shell
no log
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I will need a log to figure out the issue. Can you please provide one based on the instructions here?

If you don't know how, you can follow these steps:
1. Use a desktop/laptop to download the android platform tools from [here](https://developer.android.com/studio/releases/platform-tools).
2. Extract the downloaded file to a folder.
3. Enable USB debugging on your phone ([Instructions](https://developer.android.com/studio/command-line/adb#Enabling)), and then connect your phone to a laptop. You will get a prompt to "Allow USB debugging" when you run the logcat command. Accept this.
4. Open up a terminal/command prompt in that folder and run `./adb -d logcat AndroidRuntime:E *:S`
5. Copy and paste the output to this issue

P.S Please don't just write `no log` in the issue. That field is there for a reason, and not providing it takes me longer to identify your issue.

**Comment by xfarrow** [comment]
@OxygenCobalt I am sorry for have written "no log". Did not have a computer around. This is the log:

```
01-04 11:30:27.864 15583 15583 E AndroidRuntime: FATAL EXCEPTION: main
01-04 11:30:27.864 15583 15583 E AndroidRuntime: Process: org.oxycblt.auxio, PID: 15583
01-04 11:30:27.864 15583 15583 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2075)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1735)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5436)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:1)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:303)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:32)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at androidx.fragment.app.Fragment$10.launch(Fragment.java:11)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at org.oxycblt.auxio.music.storage.MusicDirsDialog$$ExternalSyntheticLambda4.onClick(R8$$SyntheticClass:23)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.view.View.performClick(View.java:7735)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:4)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7708)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.view.View.access$3600(View.java:848)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:29117)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:236)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8096)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
01-04 11:30:27.864 15583 15583 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

Thank you.

**Comment by OxygenCobalt** [comment]
Yep. `ACTION_DOCUMENT_TREE` is usually tied to the built-in system file manager and it is notoriously difficult to get android to recognize third-party file managers. I'll go add a check for this that will at least let the user know that no app was found that could handle it.

**Comment by xfarrow** [comment]
Thank you :)

**Comment by OxygenCobalt** [comment]
You should be able to download a debug APK [here](https://github.com/OxygenCobalt/Auxio/actions/runs/3839245197) and see if your issue is fixed.

**Comment by xfarrow** [comment]
@OxygenCobalt Yes, it does not crash any longer, thank you for your work :)

It would be so cool to be able to select the folder anyways, even tho I am afraid it's a difficult and complex task for a relatively small percentage of users ecountering this issue. 
Thank you for your work!

**Comment by OxygenCobalt** [comment]
I'm largely at the mercy of the android system for whether I can get the file picker working. You used to be able to make your own file picker, but nowadays it's no longer possible. Anyway, thanks for the report.
