### ISSUE TITLE
Crash when returning back to Auxio after a while

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#312]
### Describe the Bug/Crash

Open Auxio, play some music, pause the music, leave the app (don't close) and after a while (for me it were ~45 mins), try to go back.

### Describe the intended behavior

Just return.

### What android version do you use?

Android 12

### What device model do you use?

Stock Android (Android One)

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: org.oxycblt.auxio, PID: 19217
java.lang.NullPointerException
	at org.oxycblt.auxio.detail.DetailViewModel.requireMusic(DetailViewModel.kt:5)
	at org.oxycblt.auxio.detail.AlbumDetailFragment.onBindingCreated(AlbumDetailFragment.kt:102)
	at org.oxycblt.auxio.ui.ViewBindingFragment.onViewCreated(ViewBindingFragment.kt:42)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:303)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:154)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:308)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:154)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:308)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:154)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:308)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:154)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:34)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at org.oxycblt.auxio.MainActivity.onStart(MainActivity.kt:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1456)
	at android.app.Activity.performStart(Activity.java:8307)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3661)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Somehow the music library doesn't exist while in a part of the app where it should exist. This shouldn't be occurring at all. Do you have automatic reloading enabled?

**Comment by OxygenCobalt** [comment]
Okay, can you test this:
[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/10339860/Auxio_Canary.zip)

I did two things:
1. I stopped that code from assuming that the library exists. If it somehow does not, it gracefully degrades and exits from the album/artist/genre details view.
1. I can only assume that this is a memory issue caused by memory semantics. I tried to resolve those as best as I could.

**Comment by OxygenCobalt** [comment]
Okay, good. It is possible that the debug build did remove some of the optimizations that led to the issue, but even if the issue persists it will not crash the app anymore.
