### ISSUE TITLE
Music Loading Failed

### ISSUE THREAD

**Issue by Bubbles78959** [OxygenCobalt/Auxio#560]
### Describe the Bug/Crash

-open app 
-app says it's loading your music library
-outputs music loading failed

### Describe the intended behavior

Should list song files.

### What android version do you use?

Android 11

### What device model do you use?

Maxwest Astro 55R

### Bug report

java.lang.IllegalArgumentException: Invalid raw: No album name
	at org.oxycblt.auxio.music.device.SongImpl.<init>(SourceFile:1593)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl.create(SourceFile:216)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'm going to have to create a debug APK that allows the context of this issue to be identified. Give me some time.

**Comment by OxygenCobalt** [comment]
Okay, I finally have a debug APK available @Bubbles78959. Sorry it took so long. Can you test this and see what error it throws now?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/12923924/Auxio_Canary.zip)

**Comment by OxygenCobalt** [comment]
Closing in favor of #639, since these are likely the same issue, and I'm not getting a response here.
