### ISSUE TITLE
Idk what's happened

### ISSUE THREAD

**Issue by Shivamhobbyist** [OxygenCobalt/Auxio#596]
### Describe the Bug/Crash

Open app and see ss
![Screenshot_20231005_182419_Auxio](https://github.com/OxygenCobalt/Auxio/assets/78287172/9ba12bfd-a746-4643-acba-48b6a2f631c1)

### Describe the intended behavior

Idk

### What android version do you use?

Android 13

### What device model do you use?

Samsung One Ui android 14

### Bug report

android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service org.oxycblt.auxio/.music.system.IndexerService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at androidx.media3.common.FlagSet$Builder.tryStartForeground(SourceFile:1)
	at org.oxycblt.auxio.music.system.IndexerService.onIndexingStateChanged(SourceFile:171)
	at org.oxycblt.auxio.music.MusicRepositoryImpl.emitIndexingProgress(Unknown Source:94)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$emitIndexingProgress$1.invokeSuspend(SourceFile:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:19)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
It seems like Samsung's Android 14 release is just broken. Your phone is assuming Auxio is not allowed to load music because the user can't see the UI yet, even when that is not the case. There is nothing I can do about this. I'd recommend pressing "Retry" several times to see if the issue is temporary, otherwise, you just have to wait for Samsung to fix their buggy code.

**Comment by OxygenCobalt** [comment]
Okay, I was wrong. This is actually an issue with my app that I got away with until Android 14. See #608.
