### ISSUE TITLE
Auxio background service crashes upon speaker change

### ISSUE THREAD

**Issue by foreverxml** [OxygenCobalt/Auxio#60]
## Description

Upon connection to a Bluetooth device, Auxio tried to start the background process but for some reason it was not allowed.

(If this is not an Auxio problem feel free to close this issue.)

## Steps To Reproduce Crash

- Turn on *Headset focus*
- Connect to a Bluetooth device, specifically a (Honda) car
- See Auxio throw error (usually is silent)
- 
## Stack Trace
```
FATAL EXCEPTION: main
Process: org.oxycblt.auxio, PID: 27513
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=org.oxycblt.auxio/.playback.system.PlaybackService }: app is in background uid UidRecord{ea82d32 u0a273 TPSL bg:+12m25s117ms idle procs:0 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1861)
	at android.app.ContextImpl.startService(ContextImpl.java:1817)
	at android.content.ContextWrapper.startService(ContextWrapper.java:774)
	at android.content.ContextWrapper.startService(ContextWrapper.java:774)
	at org.oxycblt.auxio.MainActivity.onStart(MainActivity.kt:2)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1467)
	at android.app.Activity.performStart(Activity.java:8079)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3666)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7798)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

## Phone Information

Pixel 5a on Android 12L beta (S2B1.211112.006)

## Due Diligence

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Seems like an app lifecycle edge case. Can you try this APK? (Rename the extension to .apk)

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7766074/app-debug.zip)

**Comment by foreverxml** [comment]
I can't seem to reproduce the error- so I'll mark this issue closed. If it resurfaces again, I'll reopen it ;)

Have a good day!

**Comment by OxygenCobalt** [comment]
Hm. Yeah, to be technical, I think it was a race condition that resulted in android believing that the activity was in the background despite the app already being started. Stuff like that is really hard to reproduce.

**Comment by foreverxml** [comment]
It happened to me exactly *once* while I was in the middle of closing Auxio from recents.

So yeah, edge case. :/

**Comment by OxygenCobalt** [comment]
Perhaps it may be an issue with the 12L beta. I would look further into it, but I don't have access to the google issue tracker since I don't have a google account.

**Comment by foreverxml** [comment]
I have access to it; I'll look into it.
