### ISSUE TITLE
Music Loading Failed on Stock Android 14

### ISSUE THREAD

**Issue by TwirlySeal** [OxygenCobalt/Auxio#608]
### Describe the Bug/Crash

1. Open Auxio
2. Homepage displays "music loading failed"

Same bug as [#596](https://github.com/OxygenCobalt/Auxio/issues/596), but that issue was closed as specific to Samsung devices.

### Describe the intended behavior

Load music library

### What android version do you use?

Android 13

### What device model do you use?

Google Pixel 6 Pro (Stock Android 14)

### Bug report

android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service org.oxycblt.auxio/.music.system.IndexerService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at androidx.media3.common.FlagSet$Builder.tryStartForeground(SourceFile:1)
	at org.oxycblt.auxio.music.system.IndexerService.onIndexingStateChanged(SourceFile:171)
	at org.oxycblt.auxio.music.MusicRepositoryImpl.emitIndexingProgress(Unknown Source:94)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$emitIndexingProgress$1.invokeSuspend(SourceFile:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:19)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [x] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Okay, I can't assume it's device specific anymore. I actually think I know why. I'm starting the music loader when the app starts, which I thought counted as the "foreground" state and thus allowed me to do background work. I was actually supposed to be starting the music loader when the app began drawing the UI. I only got away with this because of a race condition. This is a trivial fix probably, but I have no clue when I will have the time to do it.

**Comment by OxygenCobalt** [comment]
Can you try the APK in this zip file @TwirlySeal @Gateway31 @Shivamhobbyist?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13327376/Auxio_Canary.zip)

**Comment by TwirlySeal** [comment]
That one fixed it. Works perfectly for me

**Comment by Shivamhobbyist** [comment]
> Can you try the APK in this zip file @TwirlySeal @Gateway31 @Shivamhobbyist?
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13327376/Auxio_Canary.zip)

Now it is working fine, I tried opening and closing it several times

**Comment by Gateway31** [comment]
Seems to work fine for me.

**Comment by OxygenCobalt** [comment]
Perfect! Thanks for reporting this, I'll be releasing a patch tonight.
