### ISSUE TITLE
Freezing issue

### ISSUE THREAD

**Issue by Nishantkantgaurav** [OxygenCobalt/Auxio#639]
### Describe the Bug/Crash

![Screenshot_20231214-125337_Auxio](https://github.com/OxygenCobalt/Auxio/assets/108383615/ebaed9f3-7fe9-4e39-9dd2-dfa9f5cef439)

### Describe the intended behavior

Freezing issu

### What android version do you use?

Android 14

### What device model do you use?

Mi 11x

### Bug report

java.lang.IllegalArgumentException: Invalid raw: No album name
	at org.oxycblt.auxio.music.device.SongImpl.<init>(SourceFile:1593)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl.create(SourceFile:216)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you try this APK @Nishantkantgaurav? It will still error, but it will give the name of the bad file. Please upload that file, ideally with the audio stripped out if it's copyrighted (Leave the tags/metadata).

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13693110/Auxio_Canary.zip)

**Comment by OxygenCobalt** [comment]
This is seemingly related to #560.

**Comment by OxygenCobalt** [comment]
Can you please provide a sample file @Nishantkantgaurav?

**Comment by OxygenCobalt** [comment]
Merging into #782
