### ISSUE TITLE
Cant load music

### ISSUE THREAD

**Issue by Groonir** [OxygenCobalt/Auxio#660]
### Describe the Bug/Crash

1. Install App
2. Grant music perm
3. Counter stops at last song
4. Error

### Describe the intended behavior

Should add all songs

### What android version do you use?

Android 13

### What device model do you use?

Samsung s21 Ultra magisk 

### Bug report

java.lang.IllegalStateException: Malformed song ZEDD - Ignite.flac: Artist grouping mismatch
	at org.oxycblt.auxio.music.device.DeviceLibraryImpl.<init>(SourceFile:258)
	at okhttp3.ConnectionPool.create(SourceFile:1042)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
If you can upload a sample file, that would be great. I imagine though it's just #614, which is being fixed in the next release. @Groonir

**Comment by OxygenCobalt** [comment]
Speicifcally, I want the sample file "ZEDD - Ignite.flac" @Groonir

**Comment by Groonir** [comment]
Had the same song downloaded twice lol. This caused the error. Thanks a lot!
