### ISSUE TITLE
Crash after importing any M3U file through 3rd party file manager

### ISSUE THREAD

**Issue by Thoerix** [OxygenCobalt/Auxio#700]
### Describe the Bug/Crash

After launching the app, go to the playlist tab and try to import a playlist. The native file manager will open. Click on the hamburger icon and select any 3rd party file manager. Selecting any M3U file from there will instantly crash Auxio ( Weirdly, GDrive is an exception - Auxio just refuses to load anything from it and toasts "Unable to import a playlist from this file." message )

Might be related to #693 and #673

### Describe the intended behavior

It should load it. Tested on two other devices and the result is the same

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi POCO F3

### Bug report

java.lang.IllegalArgumentException: Invalid URI: content://media/external/file/1000014949
	at android.provider.DocumentsContract.getDocumentId(DocumentsContract.java:1278)
	at org.oxycblt.auxio.music.fs.DocumentPathFactoryImpl.unpackDocumentUri(SourceFile:6)
	at org.oxycblt.auxio.music.MusicViewModel$importPlaylist$1.invokeSuspend(SourceFile:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7ee72c4, Dispatchers.IO]
	
Sometimes the URI is different, depending on the file manager. It can look something like this:
java.lang.IllegalArgumentException: Invalid URI: content://{file manager's package name}/file/{URL encoded path to the file, starting with :///storage/emulated/ }

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by MulverineX** [comment]
I'm eagerly looking forward to this 😀 (for RSAF)

**Comment by OxygenCobalt** [comment]
I actually already have a build that implements this @MulverineX, how does it work?

Only drawback here is that each loaded RSAF/other 3rd party location is treated internally as it's own "volume", which can lead to issues. Ex. if you load an M3U file that isn't in the same place as the RSAF folder but still tries to reference a folder in RSAF, it won't work. This is largely unavoidable unless I implement special URI extraction routines to pull out absolute path data (this is an utter nightmare).

[Auxio_Canary.zip](https://github.com/user-attachments/files/24841557/Auxio_Canary.zip)

(Warning: This APK will be slow because this was built for debug mode)

**Comment by OxygenCobalt** [comment]
Closing this right now, will be shipped in 4.1.0.

**Comment by MulverineX** [comment]
I know this is very late, but it works flawlessly. 👍
