### ISSUE TITLE
Error message while scanning the audio files.

### ISSUE THREAD

**Issue by stoffel010170** [OxygenCobalt/Auxio#703]
### Describe the Bug/Crash

Open app and app starts scanning 

### Describe the intended behavior

Since last version scanning of audio files don't work 

### What android version do you use?

Android 13

### What device model do you use?

Fairphone 4

### Bug report

java.lang.Exception: DeviceLibrary creation failed: java.util.concurrent.TimeoutException: Timed out receiving element from channel: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by stoffel010170** [comment]
I found the problem. Sorry
