### ISSUE TITLE
Playing a "empty" audio file stops playback completely

### ISSUE THREAD

**Issue by juuunas** [OxygenCobalt/Auxio#784]
### Describe the Bug/Crash

Play the audio attached and it will stop playback until you manually select another song.

### Describe the intended behavior

Should continue playing the next song.

### What android version do you use?

Android 12

### What device model do you use?

Google Pixel 3a (GrapheneOS)

### Provide a sample file

https://nasanoa.org/weirdfile.ogg

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Weird, will try to reproduce.

**Comment by OxygenCobalt** [comment]
I can reproduce it, but it's intentional behavior seemingly on ExoPlayer's end. Empty files probably break some invariant. I just have to indicate the error state better (See #739).

If this is an issue with a real non-empty audio file, please report this issue in the [media3 issue tracker](https://github.com/androidx/media/issues). Include the file and the stack trace @juuunas.

```
androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:687)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.common.ParserException: Loading finished before preparation is complete.{contentIsMalformed=true, dataType=1}
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod.maybeThrowPrepareError(ProgressiveMediaPeriod.java:247)
	at androidx.media3.exoplayer.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:157)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1129)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by juuunas** [comment]
> I can reproduce it, but it's intentional behavior seemingly on ExoPlayer's end. Empty files probably break some invariant. I just have to indicate the error state better (See #739).
> 
> If this is an issue with a real non-empty audio file, please report this issue in the [media3 issue tracker](https://github.com/androidx/media/issues). Include the file and the stack trace @juuunas.
> 
> ```
> androidx.media3.exoplayer.ExoPlaybackException: Source error
> 	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
> 	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:687)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loopOnce(Looper.java:205)
> 	at android.os.Looper.loop(Looper.java:294)
> 	at android.os.HandlerThread.run(HandlerThread.java:67)
> Caused by: androidx.media3.common.ParserException: Loading finished before preparation is complete.{contentIsMalformed=true, dataType=1}
> 	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod.maybeThrowPrepareError(ProgressiveMediaPeriod.java:247)
> 	at androidx.media3.exoplayer.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:157)
> 	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1129)
> 	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
> 	at android.os.Handler.dispatchMessage(Handler.java:102) 
> 	at android.os.Looper.loopOnce(Looper.java:205) 
> 	at android.os.Looper.loop(Looper.java:294) 
> 	at android.os.HandlerThread.run(HandlerThread.java:67) 
> ```

thanks for the clarification, I've been using this app for months thinking why it keeps happening - all of the files are from a specific directory so I can just exclude it anyway, thanks!
