### ISSUE TITLE
One music makes the app crash.

### ISSUE THREAD

**Issue by alletsbckwrds** [OxygenCobalt/Auxio#822]
here is the detailed exception:

```
java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Invalid raw Path(volume=InternalVolumeImpl(storageVolume=StorageVolume: Internal shared storage), components=YMusic/Ado 神っぽいな 歌いました.mp3): No album name
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

```

**Comment by OxygenCobalt** [comment]
Can you share the `YMusic/Ado 神っぽいな 歌いました.mp3` file @alletsbckwrds so I can try reproducing it?

**Comment by alletsbckwrds** [comment]
@OxygenCobalt link available for 7 days: https://www.transfernow.net/dl/20240705UAa2u9v4

**Comment by OxygenCobalt** [comment]
Can you try the APK in this ZIP @alletsbckwrds?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16114909/Auxio_Canary.zip)

**Comment by alletsbckwrds** [comment]
@OxygenCobalt it works!

**Comment by alletsbckwrds** [comment]
@OxygenCobalt wait... now it also works with the old app? what changed?? i have automatic updates off

**Comment by OxygenCobalt** [comment]
My assumption is that your phone is being inconsistent with what it returns when an audio file has no album. It might be the folder name, or it might be nothing. I've made Auxio handle the "nothing" case, so this should likely be fixed @alletsbckwrds
