### ISSUE TITLE
MUSIC LOADING FAILED

### ISSUE THREAD

**Issue by foss-** [OxygenCobalt/Auxio#823]
# DISABLE **SETTINGS -> CONTENT -> INTELLIGENT SORTING** TO FIX THIS ISSUE, RESOLUTION IS COMING ASAP

### Describe the Bug/Crash

1. update to 3.5.1
2. re-scan library
3. run into error `Music loading failed`  with `More` showing below report and `Retry` continuously failing

The error happens after the scan is almost finished and all tracks have been scanned.

### Describe the intended behavior

Scan should not fail. The scan failure seems to be a regression introduced in 3.5.1 or an existing error did not lead to a failure in 3.5.0 and earlier.

### What android version do you use?

Android 13

### What device model do you use?

lisa w ArrowOS 13.1

### Provide a sample file

N/A

### Bug report

```
java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:903)
	at java.util.TimSort.mergeAt(TimSort.java:520)
	at java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1495)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(Unknown Source:12)
	at org.oxycblt.auxio.list.sort.Sort$Mode$ByAlbum.sortSongs(SourceFile:76)
	at org.oxycblt.auxio.list.sort.Sort.songs(SourceFile:14)
	at org.oxycblt.auxio.image.extractor.Cover$Companion.order(SourceFile:8)
	at org.oxycblt.auxio.music.device.ArtistImpl.<init>(SourceFile:381)
	at okio.Path$Companion.create(SourceFile:13)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:88)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OIRNOIR** [comment]
+1 (Google Pixel 8a running GrapheneOS)

**Comment by sgreenden** [comment]
Same issue, makes the app unusable

**Comment by OxygenCobalt** [comment]
Please report error in the APK from this ZIP file @OIRNOIR @sgreenden @foss-

[Auxio_SortTrace.zip](https://github.com/user-attachments/files/16152536/Auxio_SortTrace.zip)

**Comment by OxygenCobalt** [comment]
Can you guys try out this APK @foss-  @sgreenden  @OIRNOIR 
[Auxio_Sort2.zip](https://github.com/user-attachments/files/16154264/Auxio_Sort2.zip)

**Comment by foss-** [comment]
Thanks for looking into this. Installed `Auxio_Sort2.zip` and the scan went through without failure. App can then be used as expected.

**Comment by OxygenCobalt** [comment]
Alright, seems to work then.

I've been attempting to track down the foreground issue, it's something to do with Media3. It doesn't seem to be much of an issue in production.

**Comment by foss-** [comment]
Follow-up for remaining playback problem: https://github.com/OxygenCobalt/Auxio/issues/825
