### ISSUE TITLE
Large queues cause extreme lag/out-of-memory crashes

### ISSUE THREAD

**Issue by Wjxfi** [OxygenCobalt/Auxio#842]
remove the lags please, it's impossible to use, okie ?  optimize

**Comment by OxygenCobalt** [comment]
Where does it specifically lag @Wjxfi?

**Comment by OxygenCobalt** [comment]
Screen recording @Wjxfi?

**Comment by OxygenCobalt** [comment]
Is there a version that doesnt do this @Wjxfi?

**Comment by OxygenCobalt** [comment]
Can you try old versions @Wjxfi?

**Comment by OxygenCobalt** [comment]
> > Can you try old versions @Wjxfi? Find the latest one that worked.
> 
> Sorry, I can't roll back without losing playlist data and more. long correction: there are more than two dozen of them. I'm 90% sure that everything worked 95% better than in this version - in version 3.5.0. more likely. on 3.4.3 I think everything worked for sure. @OxygenCobalt 

Can you not export all of your playlists and try 3.4.3 just in case?

**Comment by OxygenCobalt** [comment]
> Most likely it's a matter of the latest update. in f-droid after 3.5.0 comes 3.5.2

I cannot resolve your issue without a good idea of the changes that broke it. Please test older versions, just export your playlists.

**Comment by OxygenCobalt** [comment]
> I'm sure it's because of the last update and its changes. I could export normally before. @OxygenCobalt 

Can you take a bug report when these crashes happen @Wjxfi

**Comment by OxygenCobalt** [comment]
> I'm sure it's because of the last update and its changes. I could export normally before. @OxygenCobalt 
> 
> ```
> FATAL EXCEPTION: DefaultDispatcher-worker-3
> Process: org.oxycblt.auxio, PID: 1130
> java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/6499
> 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
> 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
> 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
> 	at android.content.ContentResolver.query(ContentResolver.java:1219)
> 	at android.content.ContentResolver.query(ContentResolver.java:1151)
> 	at android.content.ContentResolver.query(ContentResolver.java:1107)
> 	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:11)
> 	at org.oxycblt.auxio.music.fs.DocumentPathFactoryImpl.unpackDocumentUri(Unknown Source:52)
> 	at org.oxycblt.auxio.music.MusicViewModel$exportPlaylist$1.invokeSuspend(SourceFile:42)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
> 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
> 	at androidx.core.app.ActivityRecreator$1.run(SourceFile:40)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@aaad05a, Dispatchers.IO]
> ```
> 
> export crash log

You cannot export to the downloads folder, Auxio cannot handle those paths. Try another folder @Wjxfi

**Comment by OxygenCobalt** [comment]
Most I can tell from your logs @Wjxfi is that Auxio is using a lot of memory and struggling to garbage collect. What phone do you use? Either Auxio has a memory leak or your phone has so little memory that it simply cannot keep your library in-memory.

**Comment by OxygenCobalt** [comment]
Okay @Wjxfi, I will be sending you several APKs soon to test that will allow me to track when this issue developed. Please wait.

**Comment by foss-** [comment]
I was slightly confused to see https://github.com/OxygenCobalt/Auxio/issues/825 set to duplicated of issue 842 here. Am I understanding correctly that the crash logs I sent in 825 have changed over the testing period?

For me the behavior still feels like a crash. But maybe it is a lag (or rather memory issue), which is causing the crash?

Do you have an idea how to tackle the remaining memory issue? Not a major issue, since I can fallback to album or artist view, but song view is mostly unusable currently.

**Comment by OxygenCobalt** [comment]
Yes @foss-, the issue changed from me failing to go foreground to something apparently allocating way too much memory.

Since I cannot reproduce this, I must bisect and generate builds from various steps of the 3.5.0 development process (with the patched foreground behavior) so that I can see if the memory issue was introduced with media3 or not. Currently I don't know, since I'm 90% sure that pre-media3 debug build had the foreground glitch still in there.

**Comment by foss-** [comment]
I tested old versions to check whether 3.4.3 worked reliable. It does play tracks from Songs Category and while working rather reliably, after having Auxio open over nighty and then selecting another track from Songs it also crashed. Not sure if that is the same problem though. But after re-opening playing tracks from Songs again was possible.

**Comment by OxygenCobalt** [comment]
Can you take a bug report if it happens again @foss-? It might be that memory issue.

**Comment by OxygenCobalt** [comment]
There's no crash in the 3.4.3 report, is there any error messages from `AndroidRuntime` @foss-?

**Comment by foss-** [comment]
How would I access that? 

I tried to find relevant bits in logcat but can retry if those are missing. I tried that as no crash log was presented.The app closed itself while tapping songs from songs category.

**Comment by OxygenCobalt** [comment]
Okay @foss-, that means:
1. You didn't take the bug report at the right time, and the crash log was cleared. Not sure if this is relevant.
2. It wasn't a crash and was just...something else entirely. Sometimes if you do a weird gesture it can close the app, and if playback isn't active the app would completely shut down.

**Comment by foss-** [comment]
fair, do you need additional debug output or is the 3.5.2 crash sufficient?

**Comment by OxygenCobalt** [comment]
No, I need a crash for 3.4.3 @foss-.

Regardless, since it didn't insta-crash on playback that *must* mean something decided to start consuming way more memory in 3.5.0. My guess is media3.

**Comment by foss-** [comment]
Does this include the relevant part you are looking for? This is 3.4.3 closing while being in foreground, playing a track and selecting another track from songs category.

Please download if so, will vanish in 1 week: https://bin.disroot.org/?5a8167083cd4e27c#DXBdmkyxjd65uX3s8bEzEErAySEqfDX7iKtCZM3FKnDJ

**Comment by OxygenCobalt** [comment]
So this has existed before @foss-. It seems to be a fundamental memory issue with ExoPlayer. I think I might need to benchmark Auxio's behavior on my end by multiplying out my songs library into a huge queue and seeing what happens.

If you want, keep trying older versions until the memory issue disappears (if at all). This might help me track it down better.

**Comment by OxygenCobalt** [comment]
So I went and tested an artificial 16k-song queue on dev and it worked just fine @foss-, so either my phone just has more memory, I don't have enough songs, or there's something device specific going on.

**Comment by OxygenCobalt** [comment]
So, I think the fundamental issue I'm facing here is that at libraries of @foss- and @Wjxfi's scale, and on weak/janky enough devices, Auxio's idea of reducing latency through hosting everything in-memory completely and utterly breaks down, especially now that I have to mirror everything through Media3 and how it can stack even more of it's own memory use on.

The fundamental issue though is that moving to a latency-first model also is pretty bad, it destroys any idea of snappiness unless I put an obscene amount of hours into UI retooling. And Media3 will always be a crazy memory and CPU hog until they somehow fix that or I force-revert to MediaBrowserService (which is actually extremely tempting given how poorly the Media3 move has gone so far...)

I frankly have no clue what to do here.

**Comment by foss-** [comment]
3.5.3 crashes (expected)

Randomly tested 3.1.1 by just picking an old build and found response when playing tracks from Songs category is overall much more responsive. No choppy or briefly stuck sound, no lag after selecting a track for a few seconds before playback begins. I am unable to provoke a crash when quickly tapping various tracks from songs category AND I am unable to provoke a crash when using shuffle in the songs category.

**Comment by OxygenCobalt** [comment]
> 3.5.3 crashes (expected)
> 
> Randomly tested 3.1.1 by just picking an old build and found response when playing tracks from Songs category is overall much more responsive. No choppy or briefly stuck sound, no lag after selecting a track for a few seconds before playback begins. I am unable to provoke a crash when quickly tapping various tracks from songs category AND I am unable to provoke a crash when using shuffle in the songs category.

Okay @foss-, can you keep trying newer versions (3.2, 3.3) until things destabilize?

**Comment by OxygenCobalt** [comment]
I heard from others that ExoPlayer's gapless playback support might also cause OOMs since big MediaItem queues can trigger way too many pending tasks. In that case I might have to make that a toggle.

**Comment by foss-** [comment]
3.5.x: NOT OK
3.4.0: NOT OK
3.3.3: OK
3.3.0: OK
3.2.0: OK
3.1.1: OK

**Comment by OxygenCobalt** [comment]
Yep. It's gapless playback @foss-. That was the entire issue. The entire time. Probably @Wjxfi's fault too. Still going to dumpster Media3's session functionality since I really dislike working with it.

I need to check if there's any natural mitigation for this from the Media3 developers. Otherwise I'm going to have to either make gapless playback a setting, or dynamically turn it off when a queue is bigger than some arbitrary amount.

**Comment by OxygenCobalt** [comment]
Okay, judging by discussions with maintainers I will need to make a setting for gapless playback to resolve the instability issue, at least until the media maintainers can introduce a paging-capable player.

**Comment by OxygenCobalt** [comment]
Rolling into #957.
