### ISSUE TITLE
Music loading failed

### ISSUE THREAD

**Issue by Fuoxden** [OxygenCobalt/Auxio#905]
### Describe the Bug/Crash

I have no idea how or why its doing this, I don't really know how to replicate this bug, it happens when i open the app, it has happened a few times, i basically have to rescan the music again, witch is not a deal breaker just really annoying 

### Describe the intended behavior

well, sometimes when I launch the app it says 'music failed to load' witch, shouldn't happen

### What android version do you use?

Android 14

### What device model do you use?

Samsung a54 g5

### Provide a sample file

N/A

### Bug report

android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service org.oxycblt.auxio/.AuxioService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
	at android.app.Service.startForeground(Service.java:775)
	at org.oxycblt.auxio.music.device.SongImpl$uid$2.invoke(SourceFile:267)
	at org.oxycblt.auxio.AuxioService.updateForeground(SourceFile:182)
	at org.oxycblt.auxio.music.service.Indexer.onIndexingStateChanged(SourceFile:7)
	at org.oxycblt.auxio.music.MusicRepositoryImpl.emitIndexingProgress(Unknown Source:94)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$emitIndexingProgress$1.invokeSuspend(SourceFile:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:92)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:40)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Yeah, this just...happens. I've tried again and again and again to fix it. As far as I can tell, the magic "I'm allowed to go foreground now" variable undergoes a sub-millisecond race condition, so even when I'm at a point where I am absolutely allowed to go foreground by the documentation, it still crashes because that variable isn't flipped yet. You just have to retry again. Google does nothing about this since they don't like the idea of anyone using a foreground service ever for any reason. At most I could consider adding yet another artificial delay, but that isn't guaranteed to work and can destabilize the app in other ways. Sorry.

**Comment by Fuoxden** [comment]
ah, well i understand, that does really suck, sounds really frustrating, i hope it will be fixed someday or google will change their minds, i appreciate the response, really love the app still and will still be using it even with that little problem
