### ISSUE TITLE
Music loading failed / Android 8

### ISSUE THREAD

**Issue by mrj976** [OxygenCobalt/Auxio#95]
I get "Music loading failed" error on Android 8

Steps:
- Install app
- Press "Allow" for the storage permission prompt
- App says "Music Loading failed"
- Retry does nothing

When I test on Android 11 And 12, everything is OK and the songs load without error, but when I tested on Android 8, I encountered this problem.

Device: Xiaomei
Model: Redmi 6A
Android: 8.1

Log:
```
E/Auxio.MusicStore: Music loading failed.
E/Auxio.MusicStore: android.database.sqlite.SQLiteException: no such column: cd_track_number (code 1): , while compiling: SELECT _id, title, _display_name, cd_track_number, duration, year, album, album_id, artist, album_artist FROM audio WHERE (is_music=1)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at org.oxycblt.auxio.music.MusicLoader.loadSongs(MusicLoader.kt:134)
        at org.oxycblt.auxio.music.MusicLoader.load(MusicLoader.kt:85)
        at org.oxycblt.auxio.music.MusicStore.load(MusicStore.kt:72)
        at org.oxycblt.auxio.music.MusicStore.access$load(MusicStore.kt:41)
        at org.oxycblt.auxio.music.MusicStore$Companion$initInstance$response$1.invokeSuspend(MusicStore.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by OxygenCobalt** [comment]
Does 2.2.1 work? If that's the case, then this is actually an in-dev issue. Seems like I accidentally used a media database field only supported on Android 10 and higher [whoops].

**Comment by mrj976** [comment]
> Does 2.2.1 work? If that's the case, then this is actually an in-dev issue. Seems like I accidentally used a media database field only supported on Android 10 and higher [whoops].

Thanks. The problem was solved

**Comment by OxygenCobalt** [comment]
Cool. Thanks for reporting this before I accidentally broke the app on a bunch of devices.
